### ISSUE TITLE
Get Auth System working.

### ISSUE THREAD

**Issue by davarravad** [davarravad/UserApplePie-v-2#1]
Having an issue with the Auth system and users are not able to login.  

No error messages are displayed either.

**Comment by davarravad** [comment]
@ddmler - Can you take a look at my Auth.php and see if you can help?

**Comment by davarravad** [comment]
Changed from Cookie to Session and script is now working!  :boom:

**Comment by adjoines** [comment]
What did you change from Cookie to Session? I think I have a similar problem.

**Comment by davarravad** [comment]
I went from using the Cookie helper file to using the Session helper file within \Helpers\Auth\Auth

https://github.com/davarravad/UserApplePie-v-2/blob/master/app/Helpers/Auth/Auth.php

I just replaced Cookie:: to Session:: throughout the file.

Here is my current test site:  http://testsite.userapplepie.com/
Username: demouser
Password: demopass

I am still trying to get the error messages to work.  But I can login and logout.

**Comment by adjoines** [comment]
The thing with Session::,  a user has to sign back in each time they re-open the browser. The cookie will just be fine.  I used SMVC in a old project. But I had to hard code the cookie to last a life time.  In the project I am doing now, I want to use the Auth Addon which seems to be great. Just this weird cookie problem.

**Comment by davarravad** [comment]
Good point.  I will see what I can come up with when I get a chance.  I have never used cookies before so it will be a good lesson for me.

**Comment by davarravad** [comment]
The first time I login with a browser for the first time it works with cookie.  When I logout then try to login it does not work.  I think the cookie is not getting destroyed properly.  Looking into a solution.

**Comment by davarravad** [comment]
Found it.  Repo has been updated with changes.

**Comment by davarravad** [comment]
This has been fixed and looks to be working well.
